spring:
  application:
    name: moyeora-it-spring
  datasource:
    url: "jdbc:mysql://localhost:3306/moyedb"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # 필요시 update/create 등으로 변경
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true