management:
  endpoints:
    web:
      exposure:
        include: health, info  # 필요한 경우 "*"로 전체 노출 가능
  endpoint:
    health:
      show-details: always  # 상태 상세보기 (DB, Redis 등)

spring:
  data:
    redis:
      host: localhost
      port: 6379
#      password: 10000
  api-docs:
    enabled: true
    swagger-ui:
      path: /swagger-ui.html
      operationsSorter: method
logging:
  level:
    root: info
    com.moyeorait.moyeoraitspring: debug
