name: Deploy

on:
  push:
    branches:
      - main

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Verify Gradle version
        run: ./gradlew --version

      # gradle build
      - name: Build with Gradle
        run: ./gradlew build -x test

      # docker build & push to production
      - name: Docker build & push to prod
        if: contains(github.ref, 'main')
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/moyeoraitspring .
          docker push ${{ secrets.DOCKER_USERNAME }}/moyeoraitspring
      

      ## deploy to production
      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        id: deploy-prod
        if: contains(github.ref, 'main')
        with:
          host: ${{ secrets.HOST_PROD }} # EC2 퍼블릭 IPv4 DNS
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            # 기존 컨테이너 중지 및 삭제
            sudo docker stop moyeoraitspring || true
            sudo docker rm moyeoraitspring || true
            sudo docker ps
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/moyeoraitspring
            sudo docker run -d --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -p 8080:8080 -e spring.profiles.active="prod" -e jasypt.encryptor.password="moyeoraitkey0214" --name moyeoraitspring ${{ secrets.DOCKER_USERNAME }}/moyeoraitspring
            sudo docker image prune -f